backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "content"
    label: "Contenu du Site"
    files:
      - label: "Donn√©es Globales et Blog"
        name: "data"
        file: "data/content.json"
        fields:
          - label: "Articles de Blog"
            name: "blog_posts"
            widget: "list"
            fields:
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime" }
              - { label: "label: "Image", name: "image", widget: "image" }
              - { label: "Extrait", name: "excerpt", widget: "text" }
              - { label: "Corps de l'article", name: "body", widget: "markdown" }
